### ISSUE TITLE
Build fails with accessekit

### ISSUE THREAD

**Issue by wrnrlr** [linebender/xilem#46]
When I try to run the main example I get this error:

warning: `xilem` (bin "xilem") generated 1 warning (run `cargo fix --bin "xilem"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/xilem`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_consumer-0.13.0/src/tree.rs:150:9
stack backtrace:
   0:        0x1036fabb0 - std::backtrace_rs::backtrace::libunwind::trace::h3b2d7be4d7c482cb
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1036fabb0 - std::backtrace_rs::backtrace::trace_unsynchronized::h14e31254a2038aeb
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1036fabb0 - std::sys_common::backtrace::_print_fmt::hfa98a899dc7ee024
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1036fabb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b6a49159eed733c
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10371370c - core::fmt::write::hebe76c7e783ac2f4
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/fmt/mod.rs:1232:17
   5:        0x1036f8650 - std::io::Write::write_fmt::h030f8a3a466758ec
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/io/mod.rs:1684:15
   6:        0x1036fa9c4 - std::sys_common::backtrace::_print::h18b1b67f4250f361
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x1036fa9c4 - std::sys_common::backtrace::print::h65e42c5234fd17ad
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1036fc0a0 - std::panicking::default_hook::{{closure}}::h05ad31c0a1dad219
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:271:22
   9:        0x1036fbdf8 - std::panicking::default_hook::hdd10b9d66bfba56e
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:290:9
  10:        0x1036fc5b0 - std::panicking::rust_panic_with_hook::h456bfcb5f3345faa
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:692:13
  11:        0x1036fc4e4 - std::panicking::begin_panic_handler::{{closure}}::hf27282d367b7f23e
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:583:13
  12:        0x1036fafd0 - std::sys_common::backtrace::__rust_end_short_backtrace::ha538153f7e326fc4
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x1036fc240 - rust_begin_unwind
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:579:5
  14:        0x10373d04c - core::panicking::panic_fmt::h80bbe81c128b2f65
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:64:14
  15:        0x10373d328 - core::panicking::assert_failed_inner::hc21408cf8e4d0777
  16:        0x103739138 - core::panicking::assert_failed::h3d749fe20df4053d
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:211:5
  17:        0x10368cc10 - accesskit_consumer::tree::State::update::h301bb235d0c5f7f8
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_consumer-0.13.0/src/tree.rs:150:9
  18:        0x10368d804 - accesskit_consumer::tree::Tree::new::h29fc71210b36f80b
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_consumer-0.13.0/src/tree.rs:283:9
  19:        0x103654db4 - accesskit_macos::adapter::Adapter::new::hb30926810fb52ac6
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_macos-0.5.0/src/adapter.rs:40:20
  20:        0x103604d08 - glazier::backend::mac::window::ViewState::get_or_init_accesskit_adapter::h7bd74b1ad65e9425
                               at /Users/werner/.cargo/git/checkouts/glazier-3a172f69e2427c5a/51eb418/src/backend/mac/window.rs:1539:32
  21:        0x1036058b8 - <glazier::backend::mac::window::VIEW_CLASS as core::ops::deref::Deref>::deref::__static_ref_initialize::accessibilityFocusedUIElement::h8ef4cabc3d7afdcc
                               at /Users/werner/.cargo/git/checkouts/glazier-3a172f69e2427c5a/51eb418/src/backend/mac/window.rs:524:31
  22:        0x1987ab978 - <unknown>
  23:        0x197f9127c - <unknown>
  24:        0x197f90aa4 - <unknown>
  25:        0x197f8ff24 - <unknown>
  26:        0x19850f5ec - <unknown>
  27:        0x19850aacc - <unknown>
  28:        0x1981ca180 - <unknown>
  29:        0x1982eeaac - <unknown>
  30:        0x19832220c - <unknown>
  31:        0x1982f48e4 - <unknown>
  32:        0x1982f1620 - <unknown>
  33:        0x19af8362c - <unknown>
  34:        0x19afa8f68 - <unknown>
  35:        0x19af62d50 - <unknown>
  36:        0x19538d8c8 - <unknown>
  37:        0x19538d784 - <unknown>
  38:        0x19538bc18 - <unknown>
  39:        0x19538ab34 - <unknown>
  40:        0x19dfca338 - <unknown>
  41:        0x19dfca0b4 - <unknown>
  42:        0x19dfc9e68 - <unknown>
  43:        0x197ef251c - <unknown>
  44:        0x197ef0e14 - <unknown>
  45:        0x197ee2fe0 - <unknown>
  46:        0x1036bf010 - <() as objc::message::MessageArguments>::invoke::h518f180061bc1d03
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  47:        0x1036be348 - objc::message::platform::send_unverified::h31dbdc33cdd7b443
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  48:        0x1036b7490 - objc::message::send_message::h591f993f145e0b5b
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  49:        0x1036b7490 - <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run::h3acf5370ee2e2322
                               at /Users/werner/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.24.1/src/appkit.rs:464:9
  50:        0x1036256fc - glazier::backend::mac::application::Application::run::h3d7cdfb5176fab5d
                               at /Users/werner/.cargo/git/checkouts/glazier-3a172f69e2427c5a/51eb418/src/backend/mac/application.rs:74:13
  51:        0x10361e8f0 - glazier::application::Application::run::hee93173d2c93cc50
                               at /Users/werner/.cargo/git/checkouts/glazier-3a172f69e2427c5a/51eb418/src/application.rs:150:9
  52:        0x102d7cdbc - xilem::app_main::AppLauncher<T,V>::run::h777ded8af17741ba
                               at /Users/werner/Code/xilem/src/app_main.rs:88:9
  53:        0x102d5c414 - xilem::main::h8f5f3137ac581759
                               at /Users/werner/Code/xilem/src/main.rs:9:5
  54:        0x102d76a98 - core::ops::function::FnOnce::call_once::h39ae89c7e39195bb
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/ops/function.rs:250:5
  55:        0x102d6941c - std::sys_common::backtrace::__rust_begin_short_backtrace::h94d66ebb907998ee
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:121:18
  56:        0x102d7ee44 - std::rt::lang_start::{{closure}}::h0de383ab488e2de6
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/rt.rs:166:18
  57:        0x1036f4d9c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h475731f7094d3540
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/ops/function.rs:287:13
  58:        0x1036f4d9c - std::panicking::try::do_call::h12bf4403d16a6a4a
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:487:40
  59:        0x1036f4d9c - std::panicking::try::h18bf560b5f72e041
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:451:19
  60:        0x1036f4d9c - std::panic::catch_unwind::hcbe48bb64ad0be62
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panic.rs:140:14
  61:        0x1036f4d9c - std::rt::lang_start_internal::{{closure}}::h8e727056af92dfee
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/rt.rs:148:48
  62:        0x1036f4d9c - std::panicking::try::do_call::h79bb23a7a8fc1ffe
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:487:40
  63:        0x1036f4d9c - std::panicking::try::h6f847ef34bd6a546
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:451:19
  64:        0x1036f4d9c - std::panic::catch_unwind::h784da673948b3f7f
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panic.rs:140:14
  65:        0x1036f4d9c - std::rt::lang_start_internal::hed1c56e4b4db0361
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/rt.rs:148:20
  66:        0x102d7ee10 - std::rt::lang_start::h93ae75212f2507d9
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/rt.rs:165:17
  67:        0x102d5c448 - _main

**Comment by nicoburns** [comment]
I can reproduce this. Specifically for me it fails when clicking any of the buttons.

Failure is a panic due to a failed assertion at `accesskit_consumer-0.13.0/src/tree.rs` line 150

**Comment by raphlinus** [comment]
I've dug into this, and have an experimental patch that gets it working again. The short story is that we need to propagate HAS_ACCESSIBILITY from changes to the button text to the actual Pod flags. The long story is somewhat longer.

First, the `update` method of button does a `request_layout`, but `update` is not getting called, in part because the `ChangeFlags` from `set_label` don't include update. Even then, the update wouldn't get propagated, because update is not included in `UPWARD_FLAGS`. There's been some controversy whether update should be the main mechanism for this; it would be possible for ChangeFlags to request accessibility directly, and that might be better.

Second, there's a bit of confusion about REQUEST_ACCESSIBILITY and HAS_ACCESSIBILITY. The original plan for this is that the former means that *this* widget has requested accessibility, and the latter means some descendant has. That was propagated using special logic in `merge_up`, which was [removed](https://github.com/linebender/xilem/commit/5ecf6d5988f4a1429903c94eb00958a0934dbffe#diff-9564738fb2bbba3f2396e6c5b04e3179ea4e47269828a589eafe15b7f45f43aeL115-L117) in #40. There are a bunch of different ways to fix this:

* We can keep the two different flags in PodFlags, have widgets set REQUEST_ACCESSIBILITY, and restore the logic in `merge_up`.

* We can keep the two different flags in PodFlags, have widgets set both in their request, and include only `HAS_ACCESSIBILITY` in `UPWARD_FLAGS`.

* We can have just one flag in PodFlags, and have widgets do their own tracking of when an accessibility node is needed. The main case for this is containers, and there it's on layout change (which can be initiated by children) or structure change (which would be explicit structure change methods during mutation, associated with ChangeFlags)

Flipping a three-sided coin, any of these would work. One reason I'm responding here rather than just sending a PR is that it's important for the invariants to be communicated and documented, and I'm not sure which is the least of a footgun.

**Comment by xStrom** [comment]
The problem with widgets doing their own tracking is that people won't do it for their custom widgets. So if we can do more of the work automatically with the other options, I think that's a win.

The first option of restoring the logic seems decent to me, as it feels quite Druidish. Do we know if there was a good reason why it was removed?

Also, I did skim over those changes in #40 when it happened, but I didn't understand at a glance how those flags work. Now that you mention it, it is clear. It's similar to how is/has prefixes are used in Druid. I think renaming `HAS_ACCESSIBILITY` to say `HAS_REQUESTED_ACCESSIBILITY` or even more explicit like `DESCENDANT_HAS_REQUESTED_ACCESSIBILITY` would help prevent future confusion around these flags.

**Comment by raphlinus** [comment]
Cool, I'll consider this a vote for option 1, and agree with your reasoning.

I'm still struggling a bit with ChangeFlags. If we go the `update` route, then `merge_up` has a change to work in the update cycle. If not, in other words if we directly request accessibility from ChangeFlags, then we have a parallel set of requirements (we have to mark the PodFlags of the widget requesting accessibility with one flag, and ancestors with the other). The straightforward way to do that is to duplicate the `merge_up` logic in propagation of ChangeFlags (which is mostly implementations of `ViewSequence`), but that feels like a DRY violation.
